name: ci

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Run linter 👀
        run: yarn lint

  release:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Languages
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://raw.githubusercontent.com/quark-links/quark-server/main/utils/languages.json"
          target: assets/
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          image: docker.pkg.github.com/quark-links/quark-app/app
          tags: latest,v1
          registry: docker.pkg.github.com
          username: jakewalker
          password: ${{ secrets.DOCKER_PASSWORD }}
